### ISSUE TITLE
Support for accentuated characters (in utf8 or iso-8859-15)

### ISSUE THREAD

**Issue by dolanor** [winterstein/Eclipse-Markdown-Editor-Plugin#14]
The preview pane show problems on accentuated character.

If my file is in utf8, it shows the badly interpreted `é` interpreted as iso-8859-1.
Even in the file in iso-8859-15, it doesn't work. It seems to only handle ASCII

**Comment by paulvi** [comment]
I have been using with Chinese and there were no problems.

é is OK too

I guess this issue is too old and is to be closed.
