### ISSUE TITLE
Task tags not working in Juno

### ISSUE THREAD

**Issue by sehrgut** [winterstein/Eclipse-Markdown-Editor-Plugin#16]
I'm unable to get automatic task tags working. They aren't created out of the box, and I'm not able to get them to create with any test markers.

**Comment by paulvi** [comment]
Do you mean `- [ ]` conversion to 

- [ ] task 

That is GitHub Flavoured Markdown 

and should be addressed by https://github.com/satyagraha/gfm_viewer

ref #18
