### ISSUE TITLE
Ignore Jekyll markup 

### ISSUE THREAD

**Issue by mrpotes** [winterstein/Eclipse-Markdown-Editor-Plugin#20]
In a Jekyll markdown file there is a header that defines post attributes at the top of the file, separated by `---`, e.g.:

    ---
    author: me
    title: My blog post
    layout: default_post
    ---
    
    ## My subtitle
    {{ site.time | date_to_string }}

The Markdown HTML Preview and Markdown Editor should ignore content in this section (enabled by a preference?), and any content between double curly braces, `{{...}}` and curly-brace-percent, `{%...%}`. In the example above, the preview view renders the section at the top, and the editor displays the text from the underscore in `default_post` to the first underscore in `date_to_string` in italics, and doesn't render the heading in bold.

**Comment by paulvi** [comment]
I guess that is exactly Markdown metadata,
that is address by #49

**Comment by paulvi** [comment]
closing with #49 #52
