### ISSUE TITLE
discussion with mylyn

### ISSUE THREAD

**Issue by lxbzmy** [winterstein/Eclipse-Markdown-Editor-Plugin#28]
I download this plugin and found it's not support table extension.
And I know Mylyn already have markdown support in it's wikiText editor plugin. 
sine mylyn is a popular plugin project. can we work together to make eclipse markdown editor more powerful?

**Comment by paulvi** [comment]
I guess when README has reference for http://marketplace.eclipse.org/content/mylyn-wikitext this issue can be closed.

**Comment by paulvi** [comment]
1.2 was released, but this is unclosed and planned for 1.2

**Comment by lxbzmy** [comment]
I'm here. Sooo late four years.

**Comment by paulvi** [comment]
The comment was to Daniel @winterstein . I moved to 1.3, as 1.2 has been released before.

@lxbzmy 你好 Can you maybe comment more or open new issue, as so many comments here.
Can you develop Eclipse plugins?
Is this issue still actual?

**Comment by paulvi** [comment]
@lxbzmy BTW, take a look at https://github.com/stuarthendren/jdt.spelling

**Comment by lxbzmy** [comment]
@paulvi  You awesome, I know this plugin.
My plugin for spelling is here https://github.com/devitcn/devit-jdt  It's a simply spellcheck replace.

**Comment by paulvi** [comment]
continued at https://github.com/devitcn/devit-jdt/issues/8
