### ISSUE TITLE
[feature request] panel buton to launch GFM Viewer View

### ISSUE THREAD

**Issue by paulvi** [winterstein/Eclipse-Markdown-Editor-Plugin#42]
@satyagraha maybe could hint how Markdown preview could have icon to  launch [GFM Viewer](https://github.com/satyagraha/gfm_viewer) View (if installed)

This way, two plugins would be nicely integrated.

**Comment by paulvi** [comment]
Please remind me.

GFMV #18 is using Eclipse 4.x APIs like Part, while this plugin is not.

I wonder if code above by @satyagraha would work on Eclipse 3.x

![_markdown42](https://cloud.githubusercontent.com/assets/1614482/5699861/88e44024-9a6c-11e4-9d2e-658d3fbba329.png)

**Comment by satyagraha** [comment]
Note GFMV does not use Eclipse 4.x-specific API's or classes. The compilation problem above is easily resolved by editing the **plugin.xml** for the Winterwell editor and adding the _org.eclipse.ui.workbench entry_ to the _Required Plug-Ins_ list.

**Comment by paulvi** [comment]
@satyagraha please check/comment PR #53

**Comment by paulvi** [comment]
closing with #52 #53

**Comment by juanavelez** [comment]
Getting this error now with latest version (1.2.0.201501260515)

![screen shot 2016-01-07 at 9 06 13 am](https://cloud.githubusercontent.com/assets/7614165/12176803/031471f8-b51e-11e5-9974-6984b3afb77e.png)

**Comment by paulvi** [comment]
Do you have  [GFM Viewer](https://github.com/satyagraha/gfm_viewer) View  installed ?

**Comment by juanavelez** [comment]
That worked. Thanks

**Comment by PyvesB** [comment]
Just hit the same error message. It may be more helpful if the error message stated something along the lines of "Have you properly installed the gfm_viewer plugin?". It could also be listed as an optional dependency when installing Eclipse-Markdown-Editor-Plugin.

**Comment by paulvi** [comment]
The message is just string within this project,
welcome to change it as you like.

**Comment by paulvi** [comment]
> It could also be listed as an optional dependency when installing Eclipse-Markdown-Editor-Plugin.

It would first require to have GFM_Viewer to be in the same p2 repository as this plugin.

**Comment by PyvesB** [comment]
> 
> 
> > It could also be listed as an optional dependency when installing Eclipse-Markdown-Editor-Plugin.
> 
> It would first require to have GFM_Viewer to be in the same p2 repository as this plugin.

Are you sure about this? I noticed the following pane when defining a feature category in Eclipse RCP:

![repository](https://user-images.githubusercontent.com/10694593/56915923-9c8fc680-6aaf-11e9-8e08-38f42efafc80.png)

I've never tried configuring anything like this myself, but it does seem to imply that it's possible to link to other p2 repositories.

**Comment by paulvi** [comment]
Let's continue in new issue e.g. #83
