### ISSUE TITLE
Release 1.2

### ISSUE THREAD

**Issue by paulvi** [winterstein/Eclipse-Markdown-Editor-Plugin#52]
Thank to @oliviermartin for #48 #49 #50 #51

TODO after merging, bump version and release

**Comment by oliviermartin** [comment]
Do you know how long is going to take for this new version to be in the Eclipse Marketplace (http://marketplace.eclipse.org/content/markdown-text-editor)?

**Comment by paulvi** [comment]
Put it on http://www.nodeclipse.org/updates/markdown/

https://github.com/Nodeclipse/www.nodeclipse.org/commit/ad5261f45a7f627d71244df6d3aa227c0b84a049

Marketplace updated. Keeping this issue open for a while.

**Comment by paulvi** [comment]
Finally went with Nodeclipse train into http://www.nodeclipse.org/updates/
