### ISSUE TITLE
Treat files called *.mdwn as Markdown files

### ISSUE THREAD

**Issue by trygvis** [winterstein/Eclipse-Markdown-Editor-Plugin#57]
Ikiwiki requires the Markdown files to be called `foo.mdwn` so it would be useful if this plugin could support those files too.

**Comment by winterstein** [comment]
Hello Trygve,

I will add that.

Meanwhile, you and your existing users can set this up via Preferences->File Associations.

Best regards,
 - Daniel

**Comment by trygvis** [comment]
Thanks. I couldn't find the option when I looked yesterday but I'll try again.

**Comment by winterstein** [comment]
Status update: Done in code (ie. here in git), but no rebuild-and-publish done yet.

**Comment by paulvi** [comment]
Since Eclipse Mars, right-click any file, Open With -> Other  and in Ediotr Selection dialog check "use it for all *.ext" files"

**Comment by paulvi** [comment]
Follow in #83
