### ISSUE TITLE
Please confirm license

### ISSUE THREAD

**Issue by paulvi** [winterstein/Eclipse-Markdown-Editor-Plugin#58]
@winterstein Daniel, look at https://marketplace.eclipse.org/content/markdown-text-editor comments

What are possible licenses?

**Comment by winterstein** [comment]
Hello Paul,

I am happy with either. EPL gives a bit more freedom, shall we go with
that?

Daniel

Sent from my phone. Please excuse the brevity.

Look at https://marketplace.eclipse.org/content/markdown-text-editor
comments

What are possible licenses?

—
Reply to this email directly or view it on GitHub
<https://github.com/winterstein/Eclipse-Markdown-Editor-Plugin/issues/58>.

**Comment by winterstein** [comment]
Looking at the thread on https://marketplace.eclipse.org/content/markdown-text-editor -- I think you've fixed the listing? 
Thanks, Dan
