### ISSUE TITLE
Bash comments in block code section treated as header

### ISSUE THREAD

**Issue by bindul** [winterstein/Eclipse-Markdown-Editor-Plugin#60]
If a markdown file has a block code section with bash code snippet, the preview and outline in the plugin treats that as a heading.

Example:
---
\`\`\`
\#!/bin/bash
\# some comment
echo 'test'
\`\`\`

Is rendered as:
---
# !/bin/bash
# some comment
`echo 'test'`

Rather than
---
```
#!/bin/bash
# some comment
echo 'test'
```

**Comment by paulvi** [comment]
You need use GFM https://github.com/satyagraha/gfm_viewer for rendering

**Comment by bindul** [comment]
While GFM viewer is an option (and I will admit I have not used that feature); the markdown files I am working on are not GitHub flavoured Markdown files; they are plain Markdown files. And if I understand correctly, the issue above is not specific to GitHub flavoured markdown.

Just my 2 cents.

**Comment by paulvi** [comment]
<code>```</code> is part of GFM, not standard markdown
