### ISSUE TITLE
Cannot Install

### ISSUE THREAD

**Issue by jGleitz** [winterstein/Eclipse-Markdown-Editor-Plugin#64]
The update site of this plugin seems to be broken. Using the external install button or the Eclipse Marketplace results in this error message:

![markdown-install-error-marketplace](https://cloud.githubusercontent.com/assets/4305652/13983428/f2595ab4-f0ef-11e5-8763-1ffb4a74fe82.png)

Relevant messages from the error log are:

```
eclipse.buildId=4.5.2.M20160212-1500
java.version=1.8.0_74
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=de_DE
Framework arguments:  -product org.eclipse.epp.package.rcp.product
Command-line arguments:  -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.rcp.product

org.eclipse.equinox.p2.metadata.repository
Error
Wed Mar 23 12:05:58 CET 2016
Unable to read repository at http://www.nodeclipse.org/updates/markdown/.

java.io.IOException: http://www.nodeclipse.org/updates/markdown/ is not a valid repository location.
	at org.eclipse.equinox.internal.p2.metadata.repository.SimpleMetadataRepositoryFactory.load(SimpleMetadataRepositoryFactory.java:102)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.factoryLoad(MetadataRepositoryManager.java:57)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:768)
	at sun.reflect.GeneratedMethodAccessor82.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.oomph.util.ReflectUtil.invokeMethod(ReflectUtil.java:116)
	at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager.loadRepository(CachingRepositoryManager.java:339)
	at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager.loadRepository(CachingRepositoryManager.java:146)
	at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager$Metadata.loadRepository(CachingRepositoryManager.java:389)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:96)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:92)
	at org.eclipse.epp.internal.mpc.ui.operations.AbstractProvisioningOperation.addRepositories(AbstractProvisioningOperation.java:92)
	at org.eclipse.epp.internal.mpc.ui.operations.ProfileChangeOperationComputer.computeInstallableUnits(ProfileChangeOperationComputer.java:385)
	at org.eclipse.epp.internal.mpc.ui.operations.ProfileChangeOperationComputer.run(ProfileChangeOperationComputer.java:165)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
```
```
eclipse.buildId=4.5.2.M20160212-1500
java.version=1.8.0_74
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=de_DE
Framework arguments:  -product org.eclipse.epp.package.rcp.product
Command-line arguments:  -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.rcp.product

org.eclipse.equinox.p2.repository
Warning
Wed Mar 23 12:05:12 CET 2016
Server returned lastModified <= 0 for http://www.nodeclipse.org/updates/markdown/content.jar
```

Using the update site http://www.nodeclipse.org/updates/markdown/ in the traditional Installer gives the same messages.

**Comment by winterstein** [comment]
Hello Joshua,

Sorry about that. Our hosting partner (Nodeclipse) is looking into it.
Meanwhile, a slightly older version of the software is available from here:
<http://www.winterwell.com/software/updatesite/>
http://www.winterwell.com/software/updatesite/

Kind regards,
 - Daniel

On 23 March 2016 at 11:10, Joshua Gleitze <notifications@github.com> wrote:

> The update site of this plugin seems to be broken. Using the external
> install button or the Eclipse Marketplace results in this error message:
>
> [image: markdown-install-error-marketplace]
> <https://cloud.githubusercontent.com/assets/4305652/13983428/f2595ab4-f0ef-11e5-8763-1ffb4a74fe82.png>
>
> Relevant messages from the error log are:
>
> eclipse.buildId=4.5.2.M20160212-1500
> java.version=1.8.0_74
> java.vendor=Oracle Corporation
> BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=de_DE
> Framework arguments:  -product org.eclipse.epp.package.rcp.product
> Command-line arguments:  -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.rcp.product
>
> org.eclipse.equinox.p2.metadata.repository
> Error
> Wed Mar 23 12:05:58 CET 2016
> Unable to read repository at http://www.nodeclipse.org/updates/markdown/.
>
> java.io.IOException: http://www.nodeclipse.org/updates/markdown/ is not a valid repository location.
>     at org.eclipse.equinox.internal.p2.metadata.repository.SimpleMetadataRepositoryFactory.load(SimpleMetadataRepositoryFactory.java:102)
>     at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.factoryLoad(MetadataRepositoryManager.java:57)
>     at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:768)
>     at sun.reflect.GeneratedMethodAccessor82.invoke(Unknown Source)
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>     at java.lang.reflect.Method.invoke(Method.java:498)
>     at org.eclipse.oomph.util.ReflectUtil.invokeMethod(ReflectUtil.java:116)
>     at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager.loadRepository(CachingRepositoryManager.java:339)
>     at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager.loadRepository(CachingRepositoryManager.java:146)
>     at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager$Metadata.loadRepository(CachingRepositoryManager.java:389)
>     at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:96)
>     at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:92)
>     at org.eclipse.epp.internal.mpc.ui.operations.AbstractProvisioningOperation.addRepositories(AbstractProvisioningOperation.java:92)
>     at org.eclipse.epp.internal.mpc.ui.operations.ProfileChangeOperationComputer.computeInstallableUnits(ProfileChangeOperationComputer.java:385)
>     at org.eclipse.epp.internal.mpc.ui.operations.ProfileChangeOperationComputer.run(ProfileChangeOperationComputer.java:165)
>     at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
>
> eclipse.buildId=4.5.2.M20160212-1500
> java.version=1.8.0_74
> java.vendor=Oracle Corporation
> BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=de_DE
> Framework arguments:  -product org.eclipse.epp.package.rcp.product
> Command-line arguments:  -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.rcp.product
>
> org.eclipse.equinox.p2.repository
> Warning
> Wed Mar 23 12:05:12 CET 2016
> Server returned lastModified <= 0 for http://www.nodeclipse.org/updates/markdown/content.jar
>
> Using the update site http://www.nodeclipse.org/updates/markdown/ in the
> traditional Installer gives the same messages.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/winterstein/Eclipse-Markdown-Editor-Plugin/issues/64>
>



-- 
--------------------------------------
Dr Daniel Winterstein
Director
Edinburgh            +44 (0)772 5172 612
http://sodash.com

**Comment by paulvi** [comment]
Solved, see https://github.com/Nodeclipse/nodeclipse-1/issues/207

**Comment by paulvi** [comment]
@jGleitz Joshua there is also offline update site at https://sourceforge.net/projects/nodeclipse but not the latest version yet
