### ISSUE TITLE
Editor does not respect Eclipse Color Theme plugin

### ISSUE THREAD

**Issue by wohali** [winterstein/Eclipse-Markdown-Editor-Plugin#7]
I use a dark-colour theme from the Eclipse Color Theme plugin.
Unfortunately in the MD editor this leads to black-on-black text.
It would be great if your editor would fully support theming
based on the Eclipse Color Theme plugin @
http://eclipsecolorthemes.org

**Comment by paulvi** [comment]
This one is to be closed.

This is not issue of Markdown Editor now, but to update color mapping in ECT
https://github.com/eclipse-color-theme/eclipse-color-theme/issues/114
