### ISSUE TITLE
No repository found

### ISSUE THREAD

**Issue by dmalyuta** [winterstein/Eclipse-Markdown-Editor-Plugin#76]
I am using Ubuntu 14.04 and Eclipse Neon.3 Release (4.6.3).

I drag the "Install" button onto Eclipse Neon.3 to install this plugin, the following window shows:
![image](https://cloud.githubusercontent.com/assets/12475811/25052086/ec224ca0-2104-11e7-9945-a09a84ec45c9.png)

I click `Confirm >` and am presented with the following error:
![image](https://cloud.githubusercontent.com/assets/12475811/25052136/2a6172e8-2105-11e7-9d18-757af9930f5b.png)

So I cannot install the plugin... What is the issue?

**Comment by paulvi** [comment]
Sometimes there network issues of some users, sometime site provider has errors

There was similar issue just in March 2018,  

update site URL moved to https://nodeclipse.github.io/updates/markdown/

ref https://github.com/Nodeclipse/nodeclipse-1/issues/221

@winterstein
