### ISSUE TITLE
MD Preview Issue. Number is incorrect and Image does not show.

### ISSUE THREAD

**Issue by che1010** [winterstein/Eclipse-Markdown-Editor-Plugin#89]
We saw two issues with the Preview.

1. We have an md file with number. It has numbering 1) and 2) but the preview shows both 1)
![29372-01](https://github.com/user-attachments/assets/7fda03e9-3a58-46ca-b992-8f2e6133ed33)

2. The preview does not show the image and only shows the tags.
![29372-02](https://github.com/user-attachments/assets/0bdd7409-cdff-415d-a731-d46cd1706363)

HTML tags could be missing?
<HTML><p align="center">
. . .
</HTML></p>

**Comment by winterstein** [comment]
Hello @che1010 
Thank you for the bug report. I regret to say: I no longer maintain this plugin. Sorry I can't be of help here.
The source code is available if you want to improve it yourself.
I advice:
 - Using Eclipse's built-in Markdown support. It's not as good, but it's not bad.
 - Using a separate editor, such as Visual Studio Code.
Kind regards,
Daniel

**Comment by che1010** [comment]
This is not an issue anymore. We found that here are spacing issues in our MD file. So we can close this.
